### ISSUE TITLE
In readme, examples should be near top

### ISSUE THREAD

**Issue by benwmaddox** [benwmaddox/DataAccessGeneration#19]
The order of the sections in the readme aren't great for a quick understanding of the project

**Comment by maddy020** [comment]
Hey @benwmaddox 
I would like to work over this issue 
Please assign it to me

**Comment by benwmaddox** [comment]
@maddy020 Sure. I am new to assigning to new contributors. Please let me know if there are issues

**Comment by maddy020** [comment]
Sure @benwmaddox 
I just want to know , Am I supposed to put examples section near the top only?

**Comment by benwmaddox** [comment]
@maddy020 yup. Right after the features section, I think.

**Comment by maddy020** [comment]
Just created a PR 
Please review

**Comment by benwmaddox** [comment]
Closed. Looks good
